Add systemd service to APT package HZ-673
hazelcast/hazelcast-packaging pull request #121
Opened 2022-02-10 07:58 UTC by ldziedziul

- Adds systemd service script to deb package
- During installation adds `hazelcast` user for running the service 

APT counterpart of https://github.com/hazelcast/hazelcast-packaging/pull/120

## Testing 
- on ubuntu docker built the deb package:
```shell
HZ_DISTRIBUTION=hazelcast HZ_VERSION=5.1-SNAPSHOT PACKAGE_VERSION=5.1-SNAPSHOT ./build-hazelcast-deb-package.sh
```
- on a full-blown Ubuntu VM (docker Ubuntu doesn't have systemd):
- installed deb file `dpkg -i ./hazelcast-5.1-SNAPSHOT-all.deb` 
- tested if the following commands work: 
   - systemctl status hazelcast
   - systemctl start hazelcast
   - systemctl status hazelcast
   - systemctl stop hazelcast
   - systemctl enable hazelcast (and verify after reboot that service is up and running)
   - systemctl disable hazelcast
- tested removal of running service
   - systemctl enable hazelcast
   - systemctl start hazelcast
   - apt remove hazelcast
   - systemctl status hazelcast (verify service not found)

2022-02-10 08:02 UTC, ldziedziul commented on packages/deb/hazelcast/DEBIAN/hazelcast.service
> +[Unit]
@frant-hartm we should unify and use a single service file for both packages

2022-02-11 09:02 UTC, frant-hartm requested changes

2022-02-11 10:38 UTC, ldziedziul commented on packages/deb/hazelcast/DEBIAN/hazelcast.service
> +ExecStart=hz start
Fixed: https://github.com/hazelcast/hazelcast-packaging/pull/121/commits/04e1dfe5276ec6e8db45dac9d351f9db3caf7d64

2022-02-11 10:39 UTC, ldziedziul commented
@frant-hartm I've moved `hazelcast.service` to `packages/common/hazelcast.service`

2022-02-11 10:41 UTC, frant-hartm commented on build-hazelcast-deb-package.sh
> +cp packages/common/hazelcast.service build/deb/hazelcast/lib/systemd/system/hazelcast.service
Nice cleanup here :+1:

2022-02-11 10:42 UTC, frant-hartm approved these changes

2022-02-11 13:17 UTC, merged