Add information about Hazelcast Enterprise installation
hazelcast/hazelcast-packaging pull request #137
Opened 2022-03-16 20:16 UTC by ldziedziul

2022-03-17 09:16 UTC, kprzygudzki approved these changes

2022-03-21 12:01 UTC, frant-hartm requested changes

2022-03-21 12:01 UTC, frant-hartm commented on README.md
> +sudo apt install hazelcast-hazelcast
```suggestion
sudo apt install hazelcast-enterprise
```
?

2022-03-21 12:01 UTC, frant-hartm commented on README.md
> +sudo apt install hazelcast-hazelcast
```suggestion
sudo apt install hazelcast-enterprise
```

2022-03-21 12:12 UTC, frant-hartm approved these changes

2022-03-21 12:52 UTC, merged