[HZ-1382] Move toward Semantic versioning (X.Y.Z)
hazelcast/hazelcast-packaging pull request #152
Opened 2022-09-14 07:45 UTC by kwart

See hazelcast/hazelcast#22218 and hazelcast/hazelcast-enterprise#5290

2022-09-14 07:59 UTC, olukas approved these changes

2022-09-14 21:39 UTC, frant-hartm requested changes
Could you also update test cases in `test_common.sh` and `./packages/brew/test_brew_functions.sh` where we currently have `5.2-SNAPSHOT` in couple of places.

2022-09-15 08:25 UTC, ldziedziul commented
> Could you also update test cases in `test_common.sh` and `./packages/brew/test_brew_functions.sh` where we currently have `5.2-SNAPSHOT` in couple of places.

The same applies to BETA and DEVEL cases I think.

Also could you fix assertion message here: https://github.com/hazelcast/hazelcast-packaging/blob/d4d6a932957aaa83f6ca8a9dffbce18800eef955/test_common.sh#L70 to:

```diff
-  assert_eq "$expected" "$HZ_MINOR_VERSION" "Version $HZ_VERSION should be mapped to $HZ_MINOR_VERSION minor version" || TESTS_RESULT=$?
+  assert_eq "$expected" "$HZ_MINOR_VERSION" "Version $HZ_VERSION should be mapped to $expected minor version" || TESTS_RESULT=$?
```

2022-09-19 13:15 UTC, frant-hartm approved these changes

2022-09-19 15:45 UTC, merged